name: Deploy

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: Dokku Deploy

    steps:
      - uses: actions/checkout@v2
      
      - uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run a multi-line script
        run: |
          git remote add dokku dokku@dokku.danbee.in:me
          git push dokku
