name: Deploy

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: Dokku Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dokku.danbee.in:22/me'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
